### ISSUE TITLE
Refactor the setup

### ISSUE THREAD

**Issue by LawyZheng** [Skyvern-AI/skyvern#103]
If I update the LLM provider now, my whole env will be re-setup again, including poetry install, database install, playwright install...

As the PR https://github.com/Skyvern-AI/skyvern/pull/102 said, I simply split the functions apart. Sometimes I just want to setup some parts of the project, such as `env`, or `database`(actually my db is setup in the remote server, but I can't just execute `alembic upgrade head` and `create secrets.toml` alone).

For the long term, the setup still should be refactored by Python scripts or CLI tools to deal with more complicated commands like `docker build` for image building, `clean` for local cache cleaning, `pytest` for testing, `uninstall` for project uninstalling...

**Comment by ykeremy** [comment]
>For the long term, the setup still should be refactored by Python scripts or CLI tools to deal with more complicated commands like docker build for image building, clean for local cache cleaning, pytest for testing, uninstall for project uninstalling...

❤️❤️❤️ agreed
