### ISSUE TITLE
Getting daemon error

### ISSUE THREAD

**Issue by tulasirm** [Skyvern-AI/skyvern#1061]
Error response from daemon: Get "https://public.ecr.aws/v2/": net/http: TLS handshake timeout

**Comment by suchintan** [comment]
What command did you run to get this error?

**Comment by tulasirm** [comment]
Docker compose up ~d

**Comment by suchintan** [comment]
@tulasirm what OS?

Can you try it again? I wonder if it was a transient error to ECR

**Comment by tulasirm** [comment]
<img width="827" alt="Screen Shot 2024-11-01 at 8 11 04 AM" src="https://github.com/user-attachments/assets/7baf0545-9546-4491-ae89-ca482012e8bf">

**Comment by tulasirm** [comment]
@suchintan how to fix this above error? mine is mac OS (Monterey)

**Comment by suchintan** [comment]
This is really weird. I just ran it locally:

```
⠧ skyvern-ui Pulling                                                                                                            40.7s
   ⠴ 22d97f6a5d13 Waiting                                                                                                        38.5s
   ⠴ 2b262aa3ecfb Waiting                                                                                                        38.5s
   ⠴ d1f81d1221e9 Waiting                                                                                                        38.5s
   ⠴ 1a56272800dd Waiting                                                                                                        38.5s
   ⠴ 4d7f2d534f73 Waiting                                                                                                        38.5s
   ⠴ 10fdffda671a Waiting                                                                                                        38.5s
   ⠴ f745d7ed7efe Waiting                                                                                                        38.5s
   ⠴ e9cc7a503f7b Waiting                                                                                                        38.5s
   ⠴ b232244fb682 Waiting                                                                                                        38.5s
 ⠦ skyvern Pulling
```

It works OK. I'm also on MacOS. <br><br>What's your internet speed? Here's a page that might be helpful: [https://serverfault.com/questions/908141/docker-pull-tls-handshake-timeout](https://serverfault.com/questions/908141/docker-pull-tls-handshake-timeout)

**Comment by LawyZheng** [comment]
Are you using any VPN? Looks like it's an internet issue

**Comment by tulasirm** [comment]
Mine is 5G with 500MBPS speed. I don't think it is the internet that the
message shows as the "*TLS handshake" issue.*

**Comment by tulasirm** [comment]
Never mind, it worked today. Not sure what was wrong I have restarted my
docker daemon, all set now.

thanks
Thulasi

**Comment by suchintan** [comment]
Awesome! Glad that worked
