### ISSUE TITLE
dynamic choice of browser context

### ISSUE THREAD

**Issue by LawyZheng** [Skyvern-AI/skyvern#107]
Although `chromium-headless` and `chromium-heaful` are registered into BrowserContextFactory,
we can only choose one for all tasks(workflows) because we create the type by reading the config in env. https://github.com/Skyvern-AI/skyvern/blob/d2735100ddd38b9272e7f02ab2635493ccf9f425/skyvern/webeye/browser_factory.py#L86

Is it necessary to offer a dynamic option? maybe at the task(workflow) level? Like task(workflow) A could choose headless and task(workflow) B could choose headful?
Sure, the BROWSER_TYPE in the env config could be the default choice if not browser type is specified by the task(workflow).

**Comment by unaisshemim** [comment]
Can You assign this to me
