### ISSUE TITLE
[Bug] Container fails to start after update to v0.1.36

### ISSUE THREAD

**Issue by apvlv** [Skyvern-AI/skyvern#1077]
Logs:

> postgres-1  | 2024-10-28 19:27:36.490 UTC [1] LOG:  database system is ready to accept connections
> skyvern-1   | exec /app/entrypoint-skyvern.sh: exec format error
> skyvern-1   | exec /app/entrypoint-skyvern.sh: exec format error
> skyvern-1   | exec /app/entrypoint-skyvern.sh: exec format error
> skyvern-1   | exec /app/entrypoint-skyvern.sh: exec format error

Thank you!

**Comment by PyroFilmsFX** [comment]
Same issue here. I've been debugging this for well over an hour with no success. Claude.ai also seems to have no idea.

**Comment by 18600709862** [comment]
+1

**Comment by PyroFilmsFX** [comment]
Running on Ubuntu 20.04. Old versions issue still persists. 2 hours of debugging including using cursor with no discernible effect.

I was going to give up on my own custom design of this idea from scratch, which works, until I found this and would have built my custom functions onto it.

This setup is far too complex and convoluted. I really think this entire project can be simplified greatly without needing to whip up various bash scripts and server tools to run.

**Comment by wintonzheng** [comment]
Could you share your environments? It's most likely you're pulling the amd64 image and running in a arm machine.

Reverting the docker optimization commit here which most likely is the culprit: https://github.com/Skyvern-AI/skyvern/pull/1082. It is in the v0.1.37 release and pls try it out.

**Comment by apvlv** [comment]
@wintonzheng v0.1.37 starts healthy again! Thank you very much!

btw. i'm on an x86 intel vps server with docker and Ubuntu 22.04 LTS

**Comment by wintonzheng** [comment]
> @wintonzheng v0.1.37 starts healthy again! Thank you very much!
> 
> btw. i'm on an x86 intel vps server with docker and Ubuntu 22.04 LTS

Great to know. We’ll make sure to test that out when revisiting optimizing our image build
