### ISSUE TITLE
Wrong host in secrets.toml

### ISSUE THREAD

**Issue by LawyZheng** [Skyvern-AI/skyvern#108]
setup.sh will create the API host `http://0.0.0.0:8000/api/v1` in secrets.toml
https://github.com/Skyvern-AI/skyvern/blob/d2735100ddd38b9272e7f02ab2635493ccf9f425/setup.sh#L253
This will make UI send the request to `http://0.0.0.0:8000`, and fail to get the response in some situations (maybe firewall policy or some permission problems)

We start API listening at `0.0.0.0`, but we should access it through `localhost`, `127.0.0.1`, or `YOUR LAN IP` rather than `0.0.0.0`.

**Comment by suchintan** [comment]
localhost and 0.0.0.0 should behave the same way: https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost

**Comment by suchintan** [comment]
Surprised this is causing issues!
