### ISSUE TITLE
(solved) Web UI give no indication of working task

### ISSUE THREAD

**Issue by gwpl** [Skyvern-AI/skyvern#1093]
Steps I performed:

* Provided Skyvern OPENAI  API Key
* Run locally on Linux with docker-compose -up (with -d to see logs).
* went to Create
* created new template
* clicked "[RUN]" button

Expected behaviour:

* see indication that it's starting/started/in progress/whatever in Web UI . I was after some time clicking around as saw no indication in Tasks or any other page.

Actual behavior:

I was seeing a lot of things going on in terminal, many info logs: Calling LLM API, Action succeeded, Actions executed, Chain click starts, Updating step in db, etc... so seems like things "are happening" however are not visible in WebUI.

**Comment by gwpl** [comment]
Task seemed to finish:

```
skyvern-1     | 2024-10-30T16:09:50.625323Z [info     ] Cleaning up for task          
skyvern-1     | 2024-10-30T16:09:50.625470Z [info     ] Closing browser state         
skyvern-1     | 2024-10-30T16:09:50.625534Z [info     ] Closing browser context and its pages
skyvern-1     | 2024-10-30T16:09:52.385663Z [info     ] Main browser context and all its pages are closed
skyvern-1     | 2024-10-30T16:09:52.385756Z [info     ] Stopping playwright           
skyvern-1     | 2024-10-30T16:09:52.416807Z [info     ] Playwright is stopped         
skyvern-1     | 2024-10-30T16:09:52.416930Z [info     ] Task is cleaned up            
skyvern-1     | 2024-10-30T16:09:52.502551Z [info     ] S3 upload tasks for task_id=tsk_123456789... completed in 0.01s duration=0.012740135192871094 task_id=tsk_123456789...
skyvern-1     | 2024-10-30T16:09:52.503100Z [warning  ] Task has no webhook callback url. Not sending task response task_id=tsk_123456789....
```

why do I see in logs "S3 upload" if I did not agree to uploading any data about my activity ?
I run this locally and I expect it will only send to providers I consent (in this case I gave openai api key, so it would be this provider, but in case I would use Ollama, I would expect everything to stay locally).

Also I still do not see results in Web UI.

**Comment by LawyZheng** [comment]
The log is a mistake. We don't upload file to s3 by default. 

What do you mean you can't see anything in the UI? Can you share the screenshot?

**Comment by gwpl** [comment]
I may share screenshot, but there is really nothing there, you just see template create but no indication that task is or was running in no subpage

**Comment by gwpl** [comment]
regarding S3 line 
* it's here https://github.com/Skyvern-AI/skyvern/blob/3e0639ba3856d456b1021c208bd67fee89cdb221/skyvern/forge/sdk/artifact/manager.py#L114
* git blame points at commit : https://github.com/Skyvern-AI/skyvern/commit/9eddb3d81285a38beecadb7188d82f75dcd09295

**Comment by gwpl** [comment]
I tried again,  rebased my branch on a top of most fresh changes , run again and now it works!

Thank you! 

It so good to be alive to feel those moments when something feels like magic!

Also very important for us to have smaller and more independent alternatives to megacorp recent "take my computer" solutions! Thank you!

**Comment by suchintan** [comment]
> I tried again, rebased my branch on a top of most fresh changes , run again and now it works!
> 
> Thank you!
> 
> It so good to be alive to feel those moments when something feels like magic!
> 
> Also very important for us to have smaller and more independent alternatives to megacorp recent "take my computer" solutions! Thank you!

Thank you for these kind words!! They keep us motivated :)
