### ISSUE TITLE
Doubt Regarding CAPTCHA solving

### ISSUE THREAD

**Issue by Greatz08** [Skyvern-AI/skyvern#1117]
> **"skyvern cloud comes bundled with anti-bot detection mechanisms, proxy network, and CAPTCHA solving"**

What does anti-bot detection mechanism mean here ? Is it related to just proxies or timing based thing to make it look like human or is there different model which is trained to solve those tricky captchas that is running in cloud version ?

Tricky Website do give captchas no matter what ip you have so proxies wont work in that case and nor will timing based things so we have to solve that perfectly within time . So i guess the answer for my question is using llm model or captcha solving API's ? 

Now if any llm is solving those then is it also open source and can it be integrated with selfhosting version ?  And if using API's like max do to bypass captcha issue then is there any better plan to create llm to try to solve those captcha's with this project so that more can bypass those easily without additional subscriptions ?

**Comment by suchintan** [comment]
@Greatz08  We haven't open sourced anythign related to our captcha solver / anti-bot measures. We don't want people abusing these things, so they must remain closed source unfortunately
