### ISSUE TITLE
Documentation link redirect

### ISSUE THREAD

**Issue by sf-veer** [Skyvern-AI/skyvern#1144]
Trying to access the open source documentation at the following link redirects you to the intro page:
[https://docs.skyvern.com/getting-started/quickstart-skyvern-open-source](url)
![CleanShot 2024-11-05 at 21 55 32@2x](https://github.com/user-attachments/assets/01721977-30ca-4233-afad-c8e4ac0df835)

**Comment by suchintan** [comment]
This should be fixed!
