### ISSUE TITLE
Analysis of Skyvern on web agent Benchmarks

### ISSUE THREAD

**Issue by devinat1** [Skyvern-AI/skyvern#1207]
I am curious as to whether the Skyvern agent has been benchmarked on [webarena](https://github.com/web-arena-x/webarena) or [visualwebarena](https://github.com/web-arena-x/visualwebarena). It would be very interesting to see how the agent performs on an academic benchmark.

**Comment by suchintan** [comment]
Great idea. We're planning on doing this this month!

**Comment by alexkreidler** [comment]
Any updates on this?
