### ISSUE TITLE
[Feature Request] Send a signal to Skyvern's running process to stop the agent which sends webhook

### ISSUE THREAD

**Issue by devinat1** [Skyvern-AI/skyvern#1246]
I am running some evaluations currently on the Skyvern web agent. I set a 3 minute timeout, in which I kill the port 8000 the Skyvern process is running in. Once this happens, Skyvern doesn't send a webhook. I need the task ID sent in the webhook response, so that I can copy Skyvern's logs over to my project.

What I would like is to send a signal to Skyvern (such as through an API call) letting Skyvern know that it should halt the currently running process and send a webhook response with the details of that task as was sent in the success cases. This will avoid me having to kill the port and have no webhook response.

**Comment by suchintan** [comment]
Are you able to retrieve the task I'd when you initially start the task?

**Comment by devinat1** [comment]
@suchintan No, since its only available in the terminal I am running skyvern from. I would have to extract  text from the terminal output and regex  parse it, which is a lot of overhead.

**Comment by suchintan** [comment]
I see — you're not triggering all of the tasks remotely and relying on the webhook to alert the remote server as to the generated task ids?<br><br>It might be easier to have the script creating the tasks to just call your webhook w/ a list of task ids at the end. What do you think about that workaround?

**Comment by devinat1** [comment]
Yes that's right. The script creating the task ID's is Skyvern's own. I have no way of accessing the task ID's from the outside unless I actually go to the directory which has the name which is the task ID.

**Comment by devinat1** [comment]
How would that be achieved? Since the webhook is skyvern's.

**Comment by suchintan** [comment]
I mean: add a `curl` line to the last line of your script that calls your endpoint w/ the task ids

**Comment by suchintan** [comment]
@devinat1 I don't think we'll be working on this one (unfortunately). We don't intend to make teh docker version impervious to SIGKILL events
