### ISSUE TITLE
Webhook can't be localhost

### ISSUE THREAD

**Issue by devinat1** [Skyvern-AI/skyvern#1247]
I am wondering why the webhook is required to be a non localhost domain. In previous versions of skyvern, I was able to locally spin up a localhost flask server as a webhook receiver. Now, I have to configure [ngrok](https://ngrok.com/) to forward localhost to a static http domain, which adds cost and is unnecessary for my experiments. I understand that for sites, Skyvern could perform poorly if the domain is localhost, but the requirement for the webhook to be non-localhost doesn't make sense.

**Comment by wintonzheng** [comment]
@devinat1 
We blocked localhost in many cases including webhook for security reason. Otherwise, any user would be able to set up a localhost request to ping your server's local service or ports.

**Comment by wintonzheng** [comment]
@devinat1 
https://github.com/Skyvern-AI/skyvern/blob/6c33a6707ba5537a094d68329a29704963a6fbb6/skyvern/forge/sdk/core/validators.py#L20

would love your contributions to unblock localhost use case for development use cases
