### ISSUE TITLE
Geico Test not passing step 1

### ISSUE THREAD

**Issue by jamador47** [Skyvern-AI/skyvern#128]
Hello team, 

I have followed the installation instructions and have both

./run_skyvern.sh as well as ./run_ui.sh  executing. 

However, When trying to run ANY of the tests, It  never gets passed step 1:

![image](https://github.com/Skyvern-AI/skyvern/assets/28679489/69c0dd49-979d-44a3-b9a9-385d4e6dee5b)

As you can see, it only creates the first step and then nothing happens, Can you please assist in debugging this issue?

**Comment by jamador47** [comment]
Confirming this is occuring with ALL Test cases, not only Geico unfortunately :(

**Comment by jamador47** [comment]
Hello there @ykeremy  I have tested this in a completely new server, FYI, im using UBUNTU as a base OS for the installation (not sure if anything to do with this) and got the exact same result. After the reinstallation, I tried running as is (just after running ./setup.sh, I ran ./run_skyvern.sh and ./run_ui.sh)  and unfortunately received the same results:

![image](https://github.com/Skyvern-AI/skyvern/assets/28679489/45c719b6-3367-4a3c-b957-de56877c4b03)


After realizing I was exactly in the same position, I proceeded to do the playwright install using  command: 
`npx playwright install`

Installation was successful, unfortunately, the issue remained. 

After the installation, I re ran the ui and backend .sh and retried sending the geico from UI, a task was created, but only with step 0 once again:

![image](https://github.com/Skyvern-AI/skyvern/assets/28679489/98db470a-cf30-4f1d-9072-26828797056f)

**Comment by jamador47** [comment]
UPDATE: 

Rewatching the video sample on the main github page, I noticed a browser window is being opened. In my case, no browser is opened, what can cause this? Are there any log files I can refer to?

**Comment by jamador47** [comment]
Update:

GOT IT RUNNING! - Important lesson here, you definitely need an OS running GUI, if not, the chromium task does not seem to trigger. I was running the other tests on servers with no GUI, and therefore got the results I presented previously. Due to my last comment mentioning the browser opening, this made total sense, this needs to be executed inside the browser, if the OS cannot open a browser due to not having a GUI, it would not be able to run the tests.

Therefore, I tested installing Ubuntu 22.04 with GUI, and.... IT WORKED! :)

**Comment by ykeremy** [comment]
OH PERFECT! I was just looking into this. If you want to run it without a GUI, you can run a headless browser or simulate a display adapter.

**Comment by jamador47** [comment]
@ykeremy  thank you very much for your assistance!  this makes total sense now, just confirming, the headless browser configuration is done on the `config.py` file by changing `     BROWSER_TYPE: str = "chromium-headful"` into `    BROWSER_TYPE: str = "chromium-headless"`  is this correct?

**Comment by ykeremy** [comment]
Yes, that would work but the best way to do it is to update/add a line to your .env file with BROWSER_TYPE= chromium-headless.

I'm closing the issue since it's resolved. Feel free to ask if you have any other questions. I'll be following the thread still
