### ISSUE TITLE
Adding Gemini support

### ISSUE THREAD

**Issue by ykeremy** [Skyvern-AI/skyvern#132]
LiteLLM docs for Gemini: https://litellm.vercel.app/docs/providers/gemini

Required steps for integrating a new LLM model:

1. Define the required variables for the new models 

https://github.com/Skyvern-AI/skyvern/blob/57062952b87ab69f4688ff3f6349140acf9ed186/skyvern/config.py#L52-L72

2. Implement the configuration for the new models and register them

https://github.com/Skyvern-AI/skyvern/blob/57062952b87ab69f4688ff3f6349140acf9ed186/skyvern/forge/sdk/api/llm/config_registry.py#L57-L59

3. Update Skyvern setup script with the LLM configuration options

https://github.com/Skyvern-AI/skyvern/blob/57062952b87ab69f4688ff3f6349140acf9ed186/setup.sh#L39

**Comment by unaisshemim** [comment]
Can you assign this to me

**Comment by ykeremy** [comment]
🎉 Let us know if you have any question / need any help. Happy coding!

**Comment by unaisshemim** [comment]
Is there any thing should be changed in the .env.example file

**Comment by unaisshemim** [comment]
Is there any specific code formatter using here
