### ISSUE TITLE
Downloading PDF files freeze the agent

### ISSUE THREAD

**Issue by n-sviridenko** [Skyvern-AI/skyvern#1346]
When the agent clicks a PDF file link to download it, it opens PDF in a new tab (due to Chromium's default PDF viewer capability), this makes the agent losing the initial page (where there are other links to click) and not coming back. And then it just hangs on that PDF page forever.

**Comment by n-sviridenko** [comment]
In order to reproduce it, create a page with lots of links to PDF files and tasks Skyvern to click all of them.
It'll only visit the first PDF.

**Comment by n-sviridenko** [comment]
Btw. we also need to download PDFs instead of just viewing them.

**Comment by n-sviridenko** [comment]
Was also trying to see how downloading invoices is currently implemented https://docs.skyvern.com/getting-started/skyvern-in-action#log-into-a-portal-and-download-invoices

**Comment by n-sviridenko** [comment]
I assume implementation is:
1. subscribing to opened pages (before `await locator.click`)
2. if a new one just got opened
3. try fetching it (HEAD request, but w/ cookies of the current session, e.g. via calling `fetch`)
4. if content type from headers is PDF, then come back to prev page and download programmatically using the same URL and cookies from current session

Place to change:
https://github.com/Skyvern-AI/skyvern/blob/92d94954c4dab976ff796caa4baf65d53990ea74/skyvern/webeye/actions/handler.py#L390

**Comment by suchintan** [comment]
We actually have this implemented in Skyvern cloud similar to what you did here: https://github.com/Skyvern-AI/skyvern/pull/1349/files but I think we forgot to bring it to the open source repo

@LawyZheng can you please review https://github.com/Skyvern-AI/skyvern/pull/1349/files and make any augmentations? We should open source our PDF handling logic

**Comment by LawyZheng** [comment]
i just left some comments a few minutes ago.

**Comment by suchintan** [comment]
@LawyZheng let's get our closed source browser stuff ported over to the open source version

**Comment by LawyZheng** [comment]
Fixed in https://github.com/Skyvern-AI/skyvern/pull/1363
