### ISSUE TITLE
Organization not found when using docker compose

### ISSUE THREAD

**Issue by devinat1** [Skyvern-AI/skyvern#1395]
On Ubuntu 24, when I do docker compose up -d, I get {"detail":"Organization not found"}. The same organization ID works locally.

**Comment by suchintan** [comment]
I believe a new organization is generated when you run docker compose for the first time. Does the UI work for you?

**Comment by devinat1** [comment]
Ok, the issue was that I had to remove any files in the local setup. I did so via `git clean -fdX`. Then the docker setup and UI worked.
