### ISSUE TITLE
What is the account information of the page opened after the program is started?

### ISSUE THREAD

**Issue by mzs0207** [Skyvern-AI/skyvern#1398]
![微信截图_20241217120602](https://github.com/user-attachments/assets/88cb0017-7e28-41dc-a2df-5908f26df38f)

As shown in the picture, I have checked the relevant documents, but they are not mentioned. Please tell me the default account information or how to turn off authentication.

**Comment by wintonzheng** [comment]
@mzs0207 it doesn't look like you're on a skyvern page. pls share steps to reproduce this.

**Comment by mzs0207** [comment]
@wintonzheng  After I started with docker compose, it showed http://localhost:8080 this url.

![image](https://github.com/user-attachments/assets/a8297765-ee65-4c46-88b9-2a2b60b7a106)

**Comment by wintonzheng** [comment]
@mzs0207  8080 port is not serving another service? i do not recall we have any UI element like this. can you run `lsof -i :8080` to see which process is taking your 8080 port?

**Comment by mzs0207** [comment]
@wintonzheng Port 8080 is occupied by other services, I really feel your help.
