### ISSUE TITLE
Issue with CAPTCHA Verification 

### ISSUE THREAD

**Issue by Yasser-shrief** [Skyvern-AI/skyvern#1426]
![captcha](https://github.com/user-attachments/assets/fe839a35-ae57-4de0-921b-defcc555b454)

### CAPTCHA Verification Issue - Stuck on Puzzle

I encountered an issue while trying to use skyvern. The browsing task is stuck on a CAPTCHA verification step that requires solving a "slide puzzle" (screenshot attached) 

Have you faced this issue before? Is there a workaround or configuration to bypass or handle CAPTCHA verification during automation?

My pleasure

**Comment by Yasser-shrief** [comment]
It will be assume if Integrated with a CAPTCHA-solving tool , eg. 2captcha

**Comment by Mia-W0129** [comment]
Hello bro, How is Skyvern's service? I’m currently encountering CAPTCHA issues and looking for a solution.
