### ISSUE TITLE
Postgres in Docker not getting connected 

### ISSUE THREAD

**Issue by Arindam-FluxAuto** [Skyvern-AI/skyvern#157]
I am trying to run the skyvern after cloning from the main branch in my local windows system. I have setup all the required recommendations, as directed in [readme.md](http://readme.md) in documentation using python 3.11.

The mongodb docker got setup properly as I could see the database with tables and user are properly setup, But I couldn't see any data in the database, which are supposed to be added.
To further analyze after running the command "**poetry run python scripts/create_organization.py Skyvern-Open-Source**" I am getting errors, I am attaching the following screenshots for the further reference in this regard so that I can get & fix the root cause run skyvern tool locally from my system,

![top-part](https://uploads.linear.app/f7bc70aa-dd96-4446-9b0f-3a1642037eb9/0ece1d4f-5da0-482a-bb5c-00ffe0efe25b/44c943be-ece0-4315-9734-e5e7de886120?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y3YmM3MGFhLWRkOTYtNDQ0Ni05YjBmLTNhMTY0MjAzN2ViOS8wZWNlMWQ0Zi01ZGEwLTQ4MmEtYmI1Yy0wMGZmZTBlZmUyNWIvNDRjOTQzYmUtZWNlMC00MzE1LTk3MzQtZTVlN2RlODg2MTIwIiwiaWF0IjoxNzE0ODgwMzg1LCJleHAiOjMzMjg1NDQwMzg1fQ.EQSosZF1-pmsfB1mKC27qFb8iUI7odqpU2p2WhQ7Rog)

![bottom-part](https://uploads.linear.app/f7bc70aa-dd96-4446-9b0f-3a1642037eb9/b59cc963-3ac7-41c2-9808-c85928896185/e62b2a93-2d16-44e8-bdb5-7980d1ad8752?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y3YmM3MGFhLWRkOTYtNDQ0Ni05YjBmLTNhMTY0MjAzN2ViOS9iNTljYzk2My0zYWM3LTQxYzItOTgwOC1jODU5Mjg4OTYxODUvZTYyYjJhOTMtMmQxNi00NGU4LWJkYjUtNzk4MGQxYWQ4NzUyIiwiaWF0IjoxNzE0ODgwMzg1LCJleHAiOjMzMjg1NDQwMzg1fQ.Al8es9nM_NvsotS8QUlgbprnuUoKXSb7MoAhgUR4jjM)

**Comment by suchintan** [comment]
This is really bizarre -- it seems like we can't create organizations in your local because of an asyncio issue in windows?

**Comment by suchintan** [comment]
Does this issue still happen w/ the docker setup?

**Comment by LawyZheng** [comment]
Oh, are you trying to connect mongdb in Skyvern? I don't think postgres driver is compatible with mongodb.

**Comment by suchintan** [comment]
@Arindam-FluxAuto Are you able to use postgres instead of mongodb? Closing this for now
