### ISSUE TITLE
Posthog errors should not cause task executions to fail

### ISSUE THREAD

**Issue by hanxl1** [Skyvern-AI/skyvern#288]
hello

run run_ui.bash , failed

![Uploading 11111.png…](https://uploads.linear.app/f7bc70aa-dd96-4446-9b0f-3a1642037eb9/64491ea2-3c47-4f5c-b410-d30d88e8e17d/efa27469-56a4-41ec-8f90-5245e23ee680?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y3YmM3MGFhLWRkOTYtNDQ0Ni05YjBmLTNhMTY0MjAzN2ViOS82NDQ5MWVhMi0zYzQ3LTRmNWMtYjQxMC1kMzBkODhlOGUxN2QvZWZhMjc0NjktNTZhNC00MWVjLThmOTAtNTI0NWUyM2VlNjgwIiwiaWF0IjoxNzE1MzI4OTE5LCJleHAiOjMzMjg1ODg4OTE5fQ.guYk_i3QZNfRn2DpWvS0hg4RBAEJdyjxZkP-RxerdOM)

**Comment by ykeremy** [comment]
Hello @hanxl1, I can't see the screenshot, can you please upload it again?

**Comment by hanxl1** [comment]
> Hello @hanxl1, I can't see the screenshot, can you please upload it again?

"I'm experiencing a timeout error when attempting to create a task. The error message is 'Connection to us-api.i.posthog.com timed out.' Could you please advise on how to resolve this?" ；example:

error uploading: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fc87334c41
0>, 'Connection to us-api.i.posthog.com timed out. (connect timeout=15)'))

**Comment by LawyZheng** [comment]
Hello, @hanxl1 . This is blocking you to create a task? or it's just a error log showing on your screen ?
