### ISSUE TITLE
Skyvern front-end should report a more user-friendly message when the backend causes errors

### ISSUE THREAD

**Issue by bravet** [Skyvern-AI/skyvern#294]
<img width="1179" alt="截屏2024-05-10 16 49 36" src="https://github.com/Skyvern-AI/skyvern/assets/73118/52ad18bb-0765-4d67-8a2e-23f32dd41b71">

As shown in the figure above, when I use npm run dev to enter Local: http://localhost:8080/, a background exception occurred.

**Comment by msalihaltun** [comment]
Hey @bravet, this error can happen when the request to get running tasks results in an error. Somehow, the result is not an array. Most likely the agent service was either not available or returned something other than JSON as an error message.

Can you confirm the following:

 1. Skyvern is running (by default it runs at port 8000)
 2. You followed the quickstart in `skyvern-frontend/README.md`

Btw, we are looking into making frontend start by default alongside the agent soon with the bash scripts!
