### ISSUE TITLE
GPT-4o Integration

### ISSUE THREAD

**Issue by suchintan** [Skyvern-AI/skyvern#306]
GPT-4o launched today and it is purported to be 50% Cheaper than GPT-4V. We should set up integration with it to save our users some $$!!

https://platform.openai.com/docs/models/gpt-4o 

Example PRs on how to add new model support: https://github.com/Skyvern-AI/skyvern/pull/251/files

**Comment by syeddhasnainn** [comment]
i would like to work on this

**Comment by suchintan** [comment]
Thank you @Ghastly2001 and @syeddhasnainn for your help here!! :)
