### ISSUE TITLE
Should we have a Dockerfile as a part of the quickstart?

### ISSUE THREAD

**Issue by suchintan** [Skyvern-AI/skyvern#36]
Just went through setup with someone:
1. He had the wrong poetry env locally (poetry 1.5 instead of 1.8)
2. He had a messed up postgres directory (https://github.com/Homebrew/homebrew-core/issues/109644#issuecomment-1272514458)
3. He had conda conflicting with poetry (ended up not being a major issue)

Should we just have the quickstart be a docker image?

**Comment by nodox** [comment]
Yes we should add a dockerfile because it doesnt work on a system running python 3.12

Current error looks like such


```
.env file already exists, skipping initialization.
dyld[38115]: Library not loaded: /opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/Python
  Referenced from: <37FD4F3E-71AB-33B6-A5F0-E6DC8332F4F9> /Users/stevennatera/Library/Application Support/pypoetry/venv/bin/python
  Reason: tried: '/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/Python' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/Python' (no such file), '/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/3.11/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.11/Python' (no such file, not in dyld cache)
./setup.sh: line 61: 38115 Abort trap: 6           poetry env use python3.11
Error: Python 3.11 is not installed.
```

**Comment by suchintan** [comment]
@nodox agreed. We haven't figured out how to get a browser instance running while running this inside Docker -- keep your eyes peeled we will hopefully get it working soon!
