### ISSUE TITLE
No secrets found

### ISSUE THREAD

**Issue by Magnusretrotech** [Skyvern-AI/skyvern#391]
![image](https://github.com/Skyvern-AI/skyvern/assets/96993862/dc25eac7-602e-4cca-bc69-a985321dadab)

I get this error when running the UI

**Comment by suchintan** [comment]
@Magnusretrotech are you running this through Docker? What's your docker-compose.yml look like? (please scrub out all secrets!)

**Comment by Magnusretrotech** [comment]
I downloaded the source code and ran the setup, then the server, then the UI.

**Comment by suchintan** [comment]
What OS are you on? 
What was the setup.sh output?
