### ISSUE TITLE
Skyvern falls into a loop on many pages

### ISSUE THREAD

**Issue by devinat1** [Skyvern-AI/skyvern#400]
On many pages, such as the page newyorktimes.com with the prompt "Find the latest news", Skyvern keeps opening the same page in a loop and taking screenshots, thereafter prompting the LLM. This is with gpt-4o, but also for other models.

**Comment by suchintan** [comment]
@devinat1 What was your navigation and data extraction goal?

**Comment by gunar** [comment]
Same here, on a different URL.

Navigation:

> Navigate to each apartment's page so that you can extract the information about all apartments one by one. Only look into apartments in "XXX". Do not go to the same apartment page twice. Once you've navigated and extracted information from all apartment pages that you've found that are in XXX, your goal is COMPLETED.

Data extraction goal:

> Extract all information about each apartment for rent.

Do you have tips on how to optimize this or perhaps there's a way to prevent Skyvern from navigating to the same URL more than once?
