### ISSUE TITLE
Skyvern run_ui.sh doesn't show tasks even when skyvern is run

### ISSUE THREAD

**Issue by devinat1** [Skyvern-AI/skyvern#401]
I am getting the following when attempting to see the visualizer for tasks:

![Screenshot from 2024-05-31 18-17-57](https://uploads.linear.app/f7bc70aa-dd96-4446-9b0f-3a1642037eb9/f2934592-85b5-4ea5-8f8e-510921044bd2/d5e78725-7e15-48a4-b680-b6da723a6843?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y3YmM3MGFhLWRkOTYtNDQ0Ni05YjBmLTNhMTY0MjAzN2ViOS9mMjkzNDU5Mi04NWI1LTRlYTUtOGY4ZS01MTA5MjEwNDRiZDIvZDVlNzg3MjUtN2UxNS00OGE0LWI2ODAtYjZkYTcyM2E2ODQzIiwiaWF0IjoxNzE3MjA5MzM5LCJleHAiOjMzMjg3NzY5MzM5fQ.IZxbxYsK08_qQwL_E8voEVc_aZnosZg4g7Z8O11ZKSY)

**Comment by suchintan** [comment]
interesting. How are you running Skyvern? Are you using Docker or the contributor setup?

**Comment by devinat1** [comment]
I am using the local setup, and am running ./setup.sh, ./run_skyvern.sh followed by ./run_ui.sh.

**Comment by suchintan** [comment]
Are you running this on a Mac? Or a different OS?

**Comment by devinat1** [comment]
This is on an Ubuntu 22 machine.
Specifically:
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
