### ISSUE TITLE
LLMProvider OPENAI_GPT4O is not right here

### ISSUE THREAD

**Issue by chloecd** [Skyvern-AI/skyvern#418]
I've deployed skyvern with docker-compose which recommended here. I tried to run the example "Geico" and then got this error message. I've no idea how to fix it, could you please help this, thx a lot
 
skyvern-1    | 2024-06-05T07:00:19.614320Z [error    ] Unexpected exception in agent_step, marking step as failed step_id=stp_265805273311633576 step_order=0 step_retry=5 task_id=tsk_265804989843791896
skyvern-1    | Traceback (most recent call last):
skyvern-1    |   File "/app/skyvern/forge/sdk/api/llm/api_handler_factory.py", line 190, in llm_api_handler
skyvern-1    |     response = await litellm.acompletion(
skyvern-1    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1    |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 3609, in wrapper_async
skyvern-1    |     raise e
skyvern-1    |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 3441, in wrapper_async
skyvern-1    |     result = await original_function(*args, **kwargs)
skyvern-1    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1    |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 278, in acompletion
skyvern-1    |     _, custom_llm_provider, _, _ = get_llm_provider(
skyvern-1    |                                    ^^^^^^^^^^^^^^^^^
skyvern-1    |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 6215, in get_llm_provider
skyvern-1    |     raise e
skyvern-1    |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 6202, in get_llm_provider
skyvern-1    |     raise litellm.exceptions.BadRequestError(  # type: ignore
skyvern-1    | litellm.exceptions.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=gpt-4o
skyvern-1    |  Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
skyvern-1    |
skyvern-1    | The above exception was the direct cause of the following exception:
skyvern-1    |
skyvern-1    | Traceback (most recent call last):
skyvern-1    |   File "/app/skyvern/forge/agent.py", line 424, in agent_step
skyvern-1    |     json_response = await app.LLM_API_HANDLER(
skyvern-1    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
skyvern-1    |   File "/app/skyvern/forge/sdk/api/llm/api_handler_factory.py", line 198, in llm_api_handler
skyvern-1    |     raise LLMProviderError(llm_key) from e
skyvern-1    | skyvern.forge.sdk.api.llm.exceptions.LLMProviderError: Error while using LLMProvider OPENAI_GPT4O

**Comment by james901901** [comment]
me too

**Comment by suchintan** [comment]
@chloecd @james901901  Can you try doing `docker compose pull` ? You might be using an old image
