### ISSUE TITLE
non-OpenAI LLM APIs configuration

### ISSUE THREAD

**Issue by JawerZ** [Skyvern-AI/skyvern#487]
I am running with Docker. How can I modify the configuration file to use non-OpenAI LLM APIs, such as Kimi? And how do I add my own tasks? I don't see an entry in the UI.

**Comment by suchintan** [comment]
@JawerZ 

#1 - You can add new LLMs using this example here: https://github.com/Skyvern-AI/skyvern/issues/242#issuecomment-2092472486 

#2 - You can just edit the tasks in the UI. We're rolling out a new UI soon which will make this easier!
