### ISSUE TITLE
Templates cannot be saved in cloud

### ISSUE THREAD

**Issue by hsuperman** [Skyvern-AI/skyvern#489]
I get this error whenever trying to "Save Changes" in [app.skyvern.com](http://app.skyvern.com)

![CleanShot 2024-06-18 at 20 16 16](https://uploads.linear.app/f7bc70aa-dd96-4446-9b0f-3a1642037eb9/d4179fd5-99cc-4611-92f9-aa40fcf8eccc/e737b735-1195-495c-8dd0-8e5719b9bacc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y3YmM3MGFhLWRkOTYtNDQ0Ni05YjBmLTNhMTY0MjAzN2ViOS9kNDE3OWZkNS05OWNjLTQ2MTEtOTJmOS1hYTQwZmNmOGVjY2MvZTczN2I3MzUtMTE5NS00OTVjLThkZDAtOGU1NzE5YjliYWNjIiwiaWF0IjoxNzE4NzYxMzk0LCJleHAiOjMzMjg5MzIxMzk0fQ.0AxI7R2tEIvbRHalOTdzvTbGxDqYBcEVCd8pooUEc08)

**Comment by suchintan** [comment]
Thanks for filling this

**Comment by msalihaltun** [comment]
Hey @hsuperman, thank you for bringing this to our attention. This is definitely a bug. It should be solved with #493.
