### ISSUE TITLE
Suggestion: Allow 301 redirects

### ISSUE THREAD

**Issue by hsuperman** [Skyvern-AI/skyvern#490]
It would be nice if the URL automatically followed redirects, so for example if someone enters [https://domain.com/](https://domain.com/) instead of [https://www.domain.com/](https://www.domain.com/), it still works. Currently, it fails as pictured.

![CleanShot 2024-06-18 at 20 20 40](https://uploads.linear.app/f7bc70aa-dd96-4446-9b0f-3a1642037eb9/83c8ae18-745d-46d8-9d92-ba6fe43e0d76/0fbef510-d4c8-4438-bfb8-9e6ecbbcfa17?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y3YmM3MGFhLWRkOTYtNDQ0Ni05YjBmLTNhMTY0MjAzN2ViOS84M2M4YWUxOC03NDVkLTQ2ZDgtOWQ5Mi1iYTZmZTQzZTBkNzYvMGZiZWY1MTAtZDRjOC00NDM4LWJmYjgtOWU2ZWNiYmNmYTE3IiwiaWF0IjoxNzE4NzYxNTkxLCJleHAiOjMzMjg5MzIxNTkxfQ.2nBWwWQ6FQF7hvCImX_5C7b9aeP3IX-SSMBuxK60nyw)

**Comment by suchintan** [comment]
This is a great callout. Are you open to submitting a PR?
