### ISSUE TITLE
`frame` elements not working

### ISSUE THREAD

**Issue by ishmeals** [Skyvern-AI/skyvern#530]
Test website: https://htmledit.squarefree.com/

Element tree is empty.

I have synced up my fork to here: https://github.com/Skyvern-AI/skyvern/tree/b7af52d037a1630993ce586ee340154cf0bf3d73. This is after the iframe fix.

From my limited understanding, I believe the issue arises because iframes or frames are not being added to `element_tree` in the topmost frame.

Edit: Looks like this is just an issue with deprecated `frame` elements. This does not impact me, up to the authors whether they wanna support this.

**Comment by ykeremy** [comment]
Thanks a lot for letting us know. We'll keep an eye on failures due to `frame` elements but I don't think we'll be prioritizing it soon since:
1. you're not impacted by that 😄 
2. frames are deprecated in HTML5 as you said

**Comment by suchintan** [comment]
It might be not working because of this: https://github.com/Skyvern-AI/skyvern/blob/eb7478a58a30b13c404e08c2da60ab95ba3d43a0/skyvern/webeye/scraper/scraper.py#L451
