### ISSUE TITLE
RateLimitError: Exceeded OpenAI API Quota Leading to LLMProviderError Despite 0% Usage on Apple M2 Pro

### ISSUE THREAD

**Issue by frieda-huang** [Skyvern-AI/skyvern#546]
Hi there!

I keep getting the following errors when trying out any of the Skyvern Templates. Despite my OpenAI API usage being at 0%, I’m encountering a RateLimitError which subsequently causes an LLMProviderError when using the OPENAI_GPT4_TURBO LLM provider. I am running this on an Apple M2 Pro.

```
 File "/Users/friedahuang/Library/Caches/pypoetry/virtualenvs/skyvern-KFgdp60p-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 7779, in exception_type
    raise RateLimitError(
litellm.exceptions.RateLimitError: OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/friedahuang/Documents/skyvern/skyvern/forge/agent.py", line 520, in agent_step
    json_response = await app.LLM_API_HANDLER(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/friedahuang/Documents/skyvern/skyvern/forge/sdk/api/llm/api_handler_factory.py", line 204, in llm_api_handler
    raise LLMProviderError(llm_key) from e
skyvern.forge.sdk.api.llm.exceptions.LLMProviderError: Error while using LLMProvider OPENAI_GPT4_TURBO
```

**Steps to Reproduce**

1. Follow Quickstart instructions and run on `http://localhost:8080`.
2. Attempt to use any of the Skyvern Templates with the OpenAI API.
3. Observe the rate limit being exceeded.
4. Notice the resulting RateLimitError and the subsequent LLMProviderError.

**Comment by suchintan** [comment]
@frieda-huang we highly recommend using GPT4O if your can

**Comment by ykeremy** [comment]
Hey @frieda-huang, would you mind checking your openai account tier?

For example, [for Tier 1, gpt4 has 30k tokens per minute limit](https://platform.openai.com/docs/guides/rate-limits/usage-tiers?context=tier-one) which Skyvern can exceed depending on the webpage you're visiting. 

![image](https://github.com/Skyvern-AI/skyvern/assets/26116031/25276ab1-0a29-495c-9cdc-adf2492d8add)

You can try to increase your account tier, [here are the tier definitions](https://platform.openai.com/docs/guides/rate-limits/usage-tiers):

![image](https://github.com/Skyvern-AI/skyvern/assets/26116031/5b9eecc1-5a2a-4cce-b204-5a7473518e32)

**Comment by frieda-huang** [comment]
> Hey @frieda-huang, would you mind checking your openai account tier?
> 
> For example, [for Tier 1, gpt4 has 30k tokens per minute limit](https://platform.openai.com/docs/guides/rate-limits/usage-tiers?context=tier-one) which Skyvern can exceed depending on the webpage you're visiting.
> 
> ![image](https://private-user-images.githubusercontent.com/26116031/345651227-25276ab1-0a29-495c-9cdc-adf2492d8add.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTI2MjQsIm5iZiI6MTcyMDA1MjMyNCwicGF0aCI6Ii8yNjExNjAzMS8zNDU2NTEyMjctMjUyNzZhYjEtMGEyOS00OTVjLTljZGMtYWRmMjQ5MmQ4YWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAwMTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlOGQ1Y2VjOTFiN2ZkNGM4MjQwODRmZGFkNmM3MmRlZmNmM2I1MTk1NmI0MWI3OTIxMTQ2MzI1MzhkMjE0MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mLadP3_9N2fKwM9MsVr7Lf9IPT_JWWbrjRWul1YmuRk)
> 
> You can try to increase your account tier, [here are the tier definitions](https://platform.openai.com/docs/guides/rate-limits/usage-tiers):
> 
> ![image](https://private-user-images.githubusercontent.com/26116031/345651626-5b9eecc1-5a2a-4cce-b204-5a7473518e32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTI2MjQsIm5iZiI6MTcyMDA1MjMyNCwicGF0aCI6Ii8yNjExNjAzMS8zNDU2NTE2MjYtNWI5ZWVjYzEtNWEyYS00Y2NlLWIyMDQtNWE3NDczNTE4ZTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAwMTg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ODU1Y2FlOWU4NDEzYTBlOTkzZTM1OTc2MzljMDVmYWNhZjZlNDEzNTAxMDAzM2VjMzFkMjBiZWZhZmJhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wYc0xtula2441PlEs0ALNYHPr9N24rcOEZ2DUnZaAm4)

Thank you for the prompt response! It looks like I'm already on tier 2. 
<img width="955" alt="limit" src="https://github.com/Skyvern-AI/skyvern/assets/124417784/b993ce5e-3f57-4249-af40-bea4b0d12a13">

**Comment by frieda-huang** [comment]
It works now but flashes up the content for a split second whenever some
action is taken. It seems to get stuck when navigating the Geico site.
 Screen Recording 2024-07-10 at 9.10.42 AM.mov
<https://drive.google.com/file/d/1h3DDL3aeApvaTyu0t7HriQxcy6v9g9JS/view?usp=drive_web>
