### ISSUE TITLE
启动fastgpt的时候提示连接不上数据库

### ISSUE THREAD

**Issue by zhongliang-git** [Skyvern-AI/skyvern#563]
failed to initialize database, got error dial tcp 192.168.160.3:3306: connect:connoneapiection refused
![IMG_20240708_233403](https://github.com/Skyvern-AI/skyvern/assets/60865597/4eaa43e3-5e67-4e0c-8e5f-3843dcd949a3)

**Comment by ykeremy** [comment]
Hello, this isn't the [fastgpt repository](https://github.com/labring/FastGPT) 😅
