### ISSUE TITLE
启动fastgpt的时候提示连接不上数据库

### ISSUE THREAD

**Issue by zhongliang-git** [Skyvern-AI/skyvern#564]
failed to initialize database, got error dial tcp 192.168.160.3:3306: connect:connoneapiection refused
![Uploading IMG_20240708_233403.jpg…]()

**Comment by zhongliang-git** [comment]
![IMG_20240708_233403](https://github.com/Skyvern-AI/skyvern/assets/60865597/f2adb8a6-c944-4a6c-90d5-2260ad296de2)

**Comment by ykeremy** [comment]
Hello, this isn't the [fastgpt repository](https://github.com/labring/FastGPT) 😅
