### ISSUE TITLE
2FA login support

### ISSUE THREAD

**Issue by TheSnowGuru** [Skyvern-AI/skyvern#575]
to solve 2fa login this framework needs:
1. **human in the loop feature**  - for getting the 2fa number from authenticator by the human while in the process is running.

and a question, can this framework use a cookie for login ? i once saw this on another app....can this be added to the payload for login with cookie ?

**Comment by iloveitaly** [comment]
> and a question, can this framework use a cookie for login ? i once saw this on another app....can this be added to the payload for login with cookie

@TheSnowGuru this is cool idea. I've seen this as well. did you find a way to do this?

**Comment by santoshlite** [comment]
Would be interested in that too

**Comment by tylerdurden4285** [comment]
+1 for this please. I am trying to login to something with the credentials but it sends an email with a pin code so instead being able to login using browser cookies exported from something like "get cookies" extension would be helpful to ensure that the Skyvern workflow starts logged in by default.
