### ISSUE TITLE
Budget Management

### ISSUE THREAD

**Issue by suchintan** [Skyvern-AI/skyvern#70]
What would be nice is a simple feature where you can input the maximum number of calls / tokens to use on the entire call. Or even better, do some math and put in a dollar cap. i.e., go fill out the Geico forms for me and don't spend more than $1.00 doing it.

**Comment by ykeremy** [comment]
We're going to start using LiteLLM for LLM requests with #95. It seems they already support budgeting 🎉 

https://litellm.vercel.app/docs/budget_manager
