### ISSUE TITLE
Can't get docker image to run (docker is unhealthy)

### ISSUE THREAD

**Issue by sameerimperium** [Skyvern-AI/skyvern#725]
Hey, I stumbled upon this project and found it really cool so I followed the quick start guide and tried to get it to run. I am using it with azure open ai keys and I know the keys are correct as I have used them in another project, however when I run `docker compose -d` I get an error saying `dependency failed to start: container skyvern-skyvern-1 is unhealthy`.  The postgres and ui containers are healthy and they run perfectly. I even tried deleting all the images and container from docker desktop and running everything again but got same error again. Can anyone lemme know what I am doing wrong?

I tried starting the container from docker desktop and it ran, and I hit localhost:8080 after that, which successfully loaded the UI but I wasn't able to send any requests. Whenever I send it a request or try using the built in examples, I get a network error.

**Comment by suchintan** [comment]
@sameerimperium Can you run `docker logs` on the image and share its output?

**Comment by sameerimperium** [comment]
hey I had accidentally commented the enable azure flag in the dockerfile which was causing the issues. Fixed it after checking the logs. Thankyou.

**Comment by sameerimperium** [comment]
Just a word of warning for anyone using azure with this project, don't put the deployment URL in it. You are suppose to put in the endpoint of your organization in this and although the variable was clear in that I did not do it and it caused significant issues for me. I am guessing they are combining the variables under the hood to create the deployment URL.

**Comment by suchintan** [comment]
> Just a word of warning for anyone using azure with this project, don't put the deployment URL in it. You are suppose to put in the endpoint of your organization in this and although the variable was clear in that I did not do it and it caused significant issues for me. I am guessing they are combining the variables under the hood to create the deployment URL.

🔥🔥🔥 Glad docker logs helped! This is definitely true ,-- we construct the URL itself
