### ISSUE TITLE
How to change the openai base url?

### ISSUE THREAD

**Issue by qingmeng0906** [Skyvern-AI/skyvern#746]

**Comment by ykeremy** [comment]
We're using LiteLLM to manage different LLMs within Skyvern. Can you test this solution out by setting the env variable?

https://docs.litellm.ai/docs/providers/openai#optional-keys---openai-organization-openai-api-base

**Comment by suchintan** [comment]
You might also need to set up a new model config in the registry: https://github.com/Skyvern-AI/skyvern/blob/9e0201627b2e8308bbd2bc910bed8008563fbd95/skyvern/forge/sdk/api/llm/config_registry.py#L79

**Comment by VittorioYan** [comment]
> You might also need to set up a new model config in the registry:
> 
> https://github.com/Skyvern-AI/skyvern/blob/9e0201627b2e8308bbd2bc910bed8008563fbd95/skyvern/forge/sdk/api/llm/config_registry.py#L79

I defined the variable OPENAI_API_BASE directly, and it took effect without needing to add it to the registry.
So can we include this environment variable in the example? If I don’t look at the source code, I might not be able to find the correct way.

**Comment by suchintan** [comment]
> > You might also need to set up a new model config in the registry:
> > https://github.com/Skyvern-AI/skyvern/blob/9e0201627b2e8308bbd2bc910bed8008563fbd95/skyvern/forge/sdk/api/llm/config_registry.py#L79
> 
> I defined the variable OPENAI_API_BASE directly, and it took effect without needing to add it to the registry. So can we include this environment variable in the example? If I don’t look at the source code, I might not be able to find the correct way.

That's perfect. It's even easier than updating the LLM Config.

@VittorioYan Are you open to adding a section to the Readme to this effect?
