### ISSUE TITLE
Add uninstall script

### ISSUE THREAD

**Issue by nodox** [Skyvern-AI/skyvern#80]
There are a lot of dependencies that at install or upgraded. we need a better story on how to undo that changes by this project

**Comment by wintonzheng** [comment]
Thanks for reporting. We'll add an uninstall script.

In the meanwhile if you want to manually remove dependencies we installed:
- [poetry](https://python-poetry.org/docs/): `brew uninstall poetry`
- [postgres](https://www.postgresql.org/): `brew uninstall postgresql@14` (⚠️ Please make sure your data is backed up if you already have a local postgres installed before running skyvern)

**Comment by suchintan** [comment]
@nodox you can pretty much just delete the repo folder and most things will go away. Poetry usually installs things in a local `.env` folder (NOT to your global python!)
