### ISSUE TITLE
Add option for Azure OpenAI endpoints

### ISSUE THREAD

**Issue by illgitthat** [Skyvern-AI/skyvern#81]
Reference from the openai package: https://github.com/openai/openai-python?tab=readme-ov-file#microsoft-azure-openai

This could be handled during the setup script to set some additional environment variables, etc.

**Comment by ykeremy** [comment]
Hey thanks for creating this issue! 

I think this LLM router issue (https://github.com/Skyvern-AI/skyvern/issues/76) will introduce the flexibility you need. Our initial implementation will support Azure OpenAI and we'll add others later. I think it'll be ready by tomorrow, I'll keep this issue updated as well.

**Comment by illgitthat** [comment]
Closing this based on https://github.com/Skyvern-AI/skyvern/pull/95
